### ISSUE TITLE
Annotations in a material vs annotations dashboard

### ISSUE THREAD

**Issue by NTNUbeta** [PoeticMediaLab/LacunaStories#237]
We have discovered a discrepancy in the annotations in a material and what is displayed on the annotations dashboard when you filter by the same material. 

For some reason, when filtering by material in the annotation dashboard we get a list of students that are different from the students we see when accessing the material and browsing through the annotations. 

What could cause this? Is there a way to force update of the dashboard?

**Comment by NTNUbeta** [comment]
It appears that "Flush all caches" might have solved this. It'd be good to have in documentation + know why it is that way / what happened.

**Comment by mwidner** [comment]
For reference: the reason this happens is that it can take a long time for that data to load once a class gets into thousands of annotations. Rather than force users to wait upwards of 10 seconds, we cache that data and regenerate it every time your daily Drupal cron job runs. Or, if that's not set up, the next time somebody visits the page when the cache is over 24 hours old, the data will be regenerated.
